colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "bg.jpg"
highlightCurrentMenuArea = true
smartTOC = true

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = false
homepageImage = "bg.jpg"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = true
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showZenMode = true
heroStyle = "background"
showSummary = false



[list]
showHero = true
heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false


[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = true
showViews = true
showLikes = true
showTableOfContents = true
cardView = true

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]
  websiteId = "c254fa18-9bf9-4b84-9882-014127cbc028"
  domain = "zubayrali.xyz"
  dataDomains = "zubayrali.xyz"
  enableTrackEvent = true

[selineAnalytics]

[buymeacoffee]

[verification]
